name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Checking your code format
        run: csbt scalafmtCheckAll
      - name: Run tests
        run: csbt facade/test
