name: Scala CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Run tests
        run: csbt facade/test demo/fastOptJS::webpack demo/fastOptJS
